### ISSUE TITLE
App shortcuts

### ISSUE THREAD

**Issue by DO97** [calintat/units#5]
No more shortcuts from the recent update.
It happened just after the introduction of the new favourites feature (that didn't work on my phone).
Android 6.0.1, Nova Launcher.

What's the functionality of these favourites units?

**Comment by calintat** [comment]
I brought back the static shortcuts in the new patch v4.1.3.
The favourites feature is for choosing dynamic shortcuts which are only supported on Android 7.1.
However static shortcuts (like the ones from v4.0) work on Nova Launcher on older versions.
I was not aware of this feature of Nova Launcher which is why I removed the static shortcuts in v4.1.

**Comment by DO97** [comment]
Ok, perfect.
